id: frigate_garagem_motion_detected
alias: Frigate Motion detected Garagem
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.garagem
    zone_filter: true
    zones:
      - Garagem_Calcada
    state_filter: true
    state_entity: alarm_control_panel.ajax_security_system
    state_filter_states:
      - armed_home
    notify_group: ha_mobile_apps
    base_url: https://alberto.mcunha.me/
    message: "{{ label }} detected - {{ camera_name }}"
