id: motion_detected_tablet
alias: Motion detected - Tablet
mode: single
max_exceeded: silent
variables:
  notify_device: notify.ha_mobile_apps
  trigger_entity: binary_sensor.wallpanel_samsung_tab_s_10_5_motion_detected
  doorbell_cam: camera.wallpanel_samsung
  notification_title: Movimento Detectado
  notification_message: Tablet
  persistent_notification: false
  image_file: >-
    /local/doorbell/{{ expand(trigger_entity)[0].last_changed | as_timestamp  |
    timestamp_custom("%Y-%m-%d_%H-%M-%S-%f") }}.jpg
trigger:
  platform: state
  entity_id:
    - binary_sensor.wallpanel_samsung_tab_s_10_5_motion_detected
  # Optional
  to: "on"
  # "on" for 2 seconds
  for: "00:00:02"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.anyone_home
        state: "off"
      - condition: state
        entity_id: alarm_control_panel.ajax_security_system
        state: armed_home
action:
  - data_template:
      entity_id: camera.wallpanel_samsung
      filename: >-
        /config/www/doorbell/{{ expand(trigger_entity)[0].last_changed |
        as_timestamp  | timestamp_custom("%Y-%m-%d_%H-%M-%S-%f") }}.jpg
    service: camera.snapshot
  - service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        image: "{{ image_file }}"
        ttl: 0
        priority: high
  - delay:
      minutes: 3
