##############################################################
## Groups  ##
##############################################################

household:
  name: Household
  entities:
    - device_tracker.userone_REDACTED
    - device_tracker.REDACTED_REDACTED
    - device_tracker.userthree_REDACTED