##################################################################
## Notify Groups  ##
# https://www.home-assistant.io/integrations/group/#notify-groups
##################################################################

- platform: group
  name: "HA Mobile Apps"
  services:
    - service: 'mobile_app_samsung_s22'
    - service: 'mobile_app_oppo'