id: frigate_frente_motion_detected
alias: Frigate Motion detected Frente
description: ''
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    tv_transparency: 0%
    camera: camera.frente
    zone_filter: true
    zones:
      - Frente_Jardim
      - Frente_Portao
    state_filter: true
    state_entity: alarm_control_panel.ajax_security_system
    state_filter_states:
      - armed_home
    notify_group: ha_mobile_apps
    base_url: https://alberto.mcunha.me/
    message: '{{ label }} detected - {{ camera_name }}'
