id: motion_detected_frente_notify_s22
alias: Person or vehicle detected Frente - notify S22
description: ''
use_blueprint:
  path: hunterjm/frigate_0.10_notification.yaml
  input:
    camera: Frente
    zones:
    - Frente_Portao
    - Frente_Jardim
    notify_device: c5e66df13fa3b28125099c5a4229ddc0
