id: '1656970074919'
alias: Person or vehicle detected Garagem - notify S22
description: ''
use_blueprint:
  path: hunterjm/frigate_0.10_notification.yaml
  input:
    camera: Garagem
    zones:
    - Garagem_Calcada
    notify_device: c5e66df13fa3b28125099c5a4229ddc0
