id: motion_detected_back
alias: Motion detected - Back
mode: single
max_exceeded: silent
variables:
  notify_device: notify.ha_mobile_apps
  trigger_entity: binary_sensor.traseira_smart_motion_human
  doorbell_cam: camera.traseira_sub
  notification_title: Movimento Detectado
  notification_message: Traseiras
  persistent_notification: false
  image_file: >-
    /local/doorbell/{{ expand(trigger_entity)[0].last_changed | as_timestamp  |
    timestamp_custom("%Y-%m-%d_%H-%M-%S") }}.jpg
trigger:
  platform: state
  entity_id:
    - binary_sensor.traseira_smart_motion_human
  # Optional
  from: "off"
  # Optional
  to: "on"
  # "on" for 3 seconds
  for: "00:00:03"
condition:
  - condition: state
    entity_id: input_boolean.anyone_home
    state: "off"
action:
  - data_template:
      entity_id: camera.traseira_sub
      filename: >-
        /config/www/doorbell/{{ expand(trigger_entity)[0].last_changed |
        as_timestamp  | timestamp_custom("%Y-%m-%d_%H-%M-%S") }}.jpg
    service: camera.snapshot
  - service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        image: "{{ image_file }}"
        ttl: 0
        priority: high
  - delay:
      minutes: 3
