id: send_notification_high_humidy_wc_suite
alias: Send notification if humitidy of WC Suite is high
mode: restart
max_exceeded: silent
variables:
  notification_title: Humidade WC Suite
  persistent_notification: true
trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_temperature_humidity_wc_suite_humidity
    for:
      hours: 0
      minutes: 15
      seconds: 0
    above: 90
  - platform: time_pattern
    minutes: /10
condition:
  - condition: numeric_state
    entity_id: sensor.sensor_temperature_humidity_wc_suite_humidity
    above: 90
action:
  - alias: Set up variables for the actions
    variables:
      action_ack: "{{ 'ACK_' ~ context.id }}"
      message: "{{ 'Humidade na WC Suite demasiado alta: ' ~ states('sensor.sensor_temperature_humidity_wc_suite_humidity')  ~ '%. Liga a ventilação.'}}"
  - alias: Send notification
    service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: "{{ message }}"
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        ttl: 0
        priority: high
        actions:
          - action: "{{ action_ack }}"
            title: OK
  - alias: Wait for a response
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_ack }}"
