id: set_anyone_home_on
alias: Anyone at home ON
description: "Set set_anyone_home to on when anyone is at home"
mode: single
trigger:
  - platform: state
    entity_id:
      - person.darlene_parreira
      - person.marco
    to: home
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.marco
        state: home
      - condition: state
        entity_id: person.darlene_parreira
        state: home
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.anyone_home
