id: set_anyone_home_off
alias: Anyone at home OFF
description: "Set anyone_home to OFF when both are not at home"
mode: single
trigger:
  - platform: state
    entity_id:
      - person.marco_cunha
      - person.darlene_parreira
    to: not_home
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: person.marco_cunha
        state: not_home
      - condition: state
        entity_id: person.darlene_parreira
        state: not_home
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.anyone_home
