id: turn_on_swimming_pool_pump_according_to_energy_usage
alias: Turn on swimming pool pump according to the energy usage
description: "Turn on swimming pool pump according to the energy usage"
mode: single
variables:
  notify_device: notify.ha_mobile_apps
  notification_title: Bomba da Piscina
  persistent_notification: false
trigger:
  - platform: numeric_state
    entity_id: sensor.average_consumption_inc_pool_pump
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: -500
    alias: Enough energy to have the swimming pool pump working
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{states('sensor.swimming_pool_pump_on_today') <= states('input_number.swimming_pool_minimum_duration_h')}}"
        alias: Swimming Pool pump working for less than X time
      - condition: numeric_state
        entity_id: sensor.average_consumption_inc_pool_pump
        below: -500
        alias: Enough energy to have the swimming pool pump working
      - condition: numeric_state
        entity_id: sensor.bomba_piscina_switch_0_power
        below: 0.1
        alias: Pump turned off
      # Ask only after 9am
      - condition: time
        after: "09:00:00"
action:
  - alias: Inform swimming pool pump was turned on
    service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: Bomba da piscina ligada
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        ttl: 0
        priority: high
  - alias: Perform the action
    service: switch.turn_on
    target:
      device_id: 11352414f861aaceba25adee16b975f5
