id: turn_off_swimming_pool_pump
alias: Turn off swimming pool pump at a fixed time
description: "Turn off swimming pool pump at a fixed time"
mode: single
trigger:
  - platform: time
    at: "12:00:00"
condition:
  - condition: numeric_state
    entity_id: sensor.bomba_piscina_switch_0_power
    above: 0
action:
  - service: switch.turn_off
    target:
      device_id: 11352414f861aaceba25adee16b975f5
  - service: timer.finish
    target:
      entity_id: timer.swimming_pool_pump
