id: turn_on_swimming_pool_pump
alias: Turn on swimming pool pump at a fixed time
description: "Turn on swimming pool pump at a fixed time"
mode: single
trigger:
  - platform: time
    at: "00:10:00"
condition:
  - condition: numeric_state
    entity_id: sensor.bomba_piscina_switch_0_power
    below: 0.1
action:
  - service: switch.turn_on
    target:
      device_id: 11352414f861aaceba25adee16b975f5
  - service: timer.start
    target:
      entity_id: timer.swimming_pool_pump
