id: turn_on_christmas_tree
alias: Turn on christmas tree
description: "Turn on christmas tree if anyone at home after sunset"
mode: single
trigger:
  - platform: sun
    # Possible values: sunset, sunrise
    event: sunset
    # Optional time offset. This example will trigger 20 minutes after sunset.
    offset: "00:20:00"
  - platform: state
    entity_id:
      - input_boolean.anyone_home
    to: "on"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.anyone_home
        state: "on"
      # when dark
      - condition: sun
        after: sunset
        after_offset: "00:20:00"
        before: sunrise
      - condition: time
        before: "23:00:00"
        alias: Before 23h
action:
  - type: turn_on
    device_id: 5ba8c8993aef8a0ad6b1f06452ff8288
    entity_id: switch.christmas_tree_socket_1
    domain: switch

