##############################################################
## Input Boolean  ##
##############################################################

both_home:
  name: Both at home
  icon: mdi:home

anyone_home:
  name: Anyone at home
  icon: mdi:home

guest_mode:
  name: Guest Mode
  icon: mdi:account-group

do_not_disturb:
  name: Do Not Disturb Mode
  icon: mdi:bell-off-outline
