id: notify_swimming_pool_daily_working_hours
alias: Swimming pool daily working hours
description: Send a message about the daily operation time of the swimming pool pump
variables:
  send_notification: true
  notify_device: notify.ha_mobile_apps
  notification_title: Bomba da Piscina
  persistent_notification: false
trigger:
  - platform: time_pattern
    hours: "21"
    minutes: "30"
    seconds: "0"
action:
  - alias: Inform swimming pool pump was turned off due to time usage
    service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: "{{ 'A bomba hoje trabalhou: ' ~ states('sensor.swimming_pool_pump_on_today')|float  ~ 'h.'}}"
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        ttl: 0
        priority: high