id: turn_off_hot_water_automatically
alias: Turn off Hot Water automatically
description: Turn off Hot Water automatically
mode: single
variables:
  send_notification: true
  notify_device: notify.ha_mobile_apps
  notification_title: Água Quente
  notification_message: Água Quente desligada!
  persistent_notification: false
trigger:
  - alias: When the switch is ON for the required time
    platform: state
    entity_id:
      - switch.hot_water
    to: "on"
    for:
      hours: 0
      minutes: 15
      seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
action:
  - if: "{{ send_notification == true }}"
    then:
      - alias: Inform hot water was turned off
        service: notify.ha_mobile_apps
        data:
          title: "{{ notification_title }}"
          message: "{{ notification_message }}"
          data:
            tag: "{{ notification_title }}"
            persistent: "{{ persistent_notification }}"
            ttl: 0
            priority: high
  - alias: Turn off
    service: switch.turn_off
    data: {}
    target:
      entity_id: switch.hot_water
