id: send_notification_high_humidy_wc_servico
alias: Send notification if humitidy of WC Serviço is high
mode: restart
max_exceeded: silent
variables:
  notification_title: Humidade WC Serviço
  persistent_notification: false
trigger:
  - platform: numeric_state
    entity_id: sensor.wc_temperature_humidity_sensor_humidity
    for:
      hours: 0
      minutes: 15
      seconds: 0
    above: 90
  - platform: time_pattern
    minutes: /10
condition:
  - condition: numeric_state
    entity_id: sensor.wc_temperature_humidity_sensor_humidity
    above: 90
action:
  - alias: Set up variables for the actions
    variables:
      action_ack: "{{ 'ACK_' ~ context.id }}"
      message: "{{ 'Humidade na WC Serviço demasiado alta: ' ~ states('sensor.wc_temperature_humidity_sensor_humidity')  ~ '%. Liga a ventilação.'}}"
  - alias: Send notification
    service: notify.ha_mobile_apps
    data:
      title: "{{ notification_title }}"
      message: "{{ message }}"
      data:
        tag: "{{ notification_title }}"
        persistent: "{{ persistent_notification }}"
        ttl: 0
        priority: high
