#
# Input Number

#
# https://www.home-assistant.io/integrations/input_number/
#
input_number:
  swimming_pool_minimum_duration_h:
    name: Swimming Pool Pump Minimum Duration in h
    initial: 12
    min: 0
    max: 99
    step: 1
    mode: box
  swimming_pool_average_consumption_w:
    name: Swimming Pool Pump Average Consumption in W
    initial: 750
    min: 700
    max: 800
    step: 1
    mode: box
