#
# Statistics
# The statistics sensor platform observes the state of a source sensor and provides aggregated statistical characteristics about its recent past.
#
# https://www.home-assistant.io/integrations/statistics/
sensor:
  - platform: template
    sensors:
      average_consumption_inc_pool_pump:
        value_template: >-
          {% if has_value('sensor.energy_consumption_mean_over_last_10_minutes') %}
            {% set energy_consumption_mean_over_last_10_minutes = states('sensor.energy_consumption_mean_over_last_10_minutes')| float %}
          {% else %}
            {% set energy_consumption_mean_over_last_10_minutes = 0.0 %}
          {% endif %}
          {% if has_value('input_number.swimming_pool_average_consumption_w') %}
            {% set swimming_pool_average_consumption_w = states('input_number.swimming_pool_average_consumption_w')| float %}
          {% else %}
            {% set swimming_pool_average_consumption_w = 0.0 %}
          {% endif %}

          {{ energy_consumption_mean_over_last_10_minutes + swimming_pool_average_consumption_w }}
