#
# Statistics
# The statistics sensor platform observes the state of a source sensor and provides aggregated statistical characteristics about its recent past.
#
# https://www.home-assistant.io/integrations/statistics/
sensor:
  - platform: statistics
    name: "Energy Consumption mean over last 10 minutes"
    entity_id: sensor.contador_consumo_channel_1_power
    state_characteristic: mean
    max_age:
      minutes: 10
